### ISSUE TITLE
Incorrect install on raspberry pi 4

### ISSUE THREAD

**Issue by irishgreencitrus** [Cesura/pastey#4]
when running `pip3 install -r requirements.txt` it errors out with 
```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cih8b9_z/flask_73e9fcc6aaef45e892bab6c7352ea254/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cih8b9_z/flask_73e9fcc6aaef45e892bab6c7352ea254/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-59rx5xio
         cwd: /tmp/pip-install-cih8b9_z/flask_73e9fcc6aaef45e892bab6c7352ea254/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cih8b9_z/flask_73e9fcc6aaef45e892bab6c7352ea254/setup.py", line 62
        print "Audit requires PyFlakes installed in your system."
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Audit requires PyFlakes installed in your system.")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
which is python2 syntax. it also seems to install every version of flask possible, so that's another error

**Comment by Cesura** [comment]
This seems to be a problem with flask on aarch64, no? At least, it's not pointing out a syntax error with Pastey itself.

I saw you forked the repo and removed the tensorflow requirement; does it seem like an impossible task right now to build with guesslang on a Pi?

**Comment by irishgreencitrus** [comment]
> This seems to be a problem with flask on aarch64, no? At least, it's not pointing out a syntax error with Pastey itself.
> 
> I saw you forked the repo and removed the tensorflow requirement; does it seem like an impossible task right now to build with guesslang on a Pi?

the issue is that by just putting flask in requirements.txt, it wants to install every single version of flask it can. you need to specify a version. tensorflow seems unreasonable to me for a designed to be simple pasting tool. there's also languages with quite similar syntax which it could struggle with

**Comment by Cesura** [comment]
> the issue is that by just putting flask in requirements.txt, it wants to install every single version of flask it can. you need to specify a version.

While pinning versions is a good idea and something I will indeed add to the requirements file per your pull request, that's not the reason pip is going through each version of the package. Under normal circumstances, it will install the latest version, unless it encounters dependency resolving issues, in which case it will keep trying until one fits the requirements.

Are you saying that when you run **pip install flask** it attempts every version (including 1.1.2) and fails, but **pip install flask==1.1.2** works for you?

**Comment by irishgreencitrus** [comment]
yes that's what i'm saying
