### ISSUE TITLE
Trying to open any file in the DATA dir as JSON can break on certain setups

### ISSUE THREAD

**Issue by srgvg** [Cesura/pastey#7]
I run pastey on Kubernetes, and the data/ dir has en persistent volume mounted on it. As such, it has the typical `lost+found` directory in its root, and pastey breaks on it:

```
[2021-04-15 20:58:09,606] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/pastey/routes.py", line 25, in home
    pastes = functions.get_recent()
  File "/app/pastey/functions.py", line 21, in get_recent
    with open(paths[i]) as fp:
IsADirectoryError: [Errno 21] Is a directory: '/data/lost+found'
```

I would suggest updating `pastey.functions.get_recent` with some error proof coding for this.

**Comment by Cesura** [comment]
Very silly oversight on my part. Thanks for the report, I'll update soon.

**Comment by Cesura** [comment]
Fixed in:
https://github.com/Cesura/pastey/commit/683143d7ad07f55ee782865032749895e42284ed

**Comment by srgvg** [comment]
Thanks you, just deployed the new version, and that works flawlessly now. Also scaling to two pods works as expected now.
